import dotenv from 'dotenv'
import connectDB from '../config/database'
import Food from '../models/Food'

// Load environment variables
dotenv.config()

const commonFoods = [
  {
    name: 'Egg',
    brand: 'Generic',
    calories_per_100g: 155,
    protein_per_100g: 13,
    carbs_per_100g: 1.1,
    fat_per_100g: 11,
    serving_sizes: [
      { unit: 'medium egg', grams: 44, label: '1 medium egg (44g)' },
      { unit: 'large egg', grams: 50, label: '1 large egg (50g)' },
      { unit: 'extra large egg', grams: 56, label: '1 extra large egg (56g)' },
    ],
    source: 'usda',
  },

  {
    name: 'Egg White',
    brand: 'Generic',
    calories_per_100g: 52,
    protein_per_100g: 11,
    carbs_per_100g: 0.7,
    fat_per_100g: 0.2,
    serving_sizes: [
      { unit: 'egg white', grams: 33, label: '1 egg white (33g)' },
      { unit: 'egg whites', grams: 66, label: '2 egg whites (66g)' },
      { unit: 'egg whites', grams: 99, label: '3 egg whites (99g)' },
    ],
    source: 'usda',
  },

  {
    name: 'Banana',
    brand: 'Generic',
    calories_per_100g: 89,
    protein_per_100g: 1.1,
    carbs_per_100g: 23,
    fat_per_100g: 0.3,
    serving_sizes: [
      { unit: 'small banana', grams: 101, label: '1 small banana' },
      { unit: 'medium banana', grams: 118, label: '1 medium banana' },
      { unit: 'large banana', grams: 136, label: '1 large banana' },
    ],
    source: 'usda',
  },

  {
    name: 'Apple',
    brand: 'Generic',
    calories_per_100g: 52,
    protein_per_100g: 0.3,
    carbs_per_100g: 14,
    fat_per_100g: 0.2,
    serving_sizes: [{ unit: 'apple', grams: 182, label: '1 apple (182g)' }],
    source: 'usda',
  },

  {
    name: 'Orange',
    brand: 'Generic',
    calories_per_100g: 47,
    protein_per_100g: 0.9,
    carbs_per_100g: 12,
    fat_per_100g: 0.1,
    serving_sizes: [{ unit: 'orange', grams: 130, label: '1 orange' }],
    source: 'usda',
  },

  {
    name: 'Roti',
    brand: 'Generic',
    calories_per_100g: 297,
    protein_per_100g: 11,
    carbs_per_100g: 49,
    fat_per_100g: 7,
    serving_sizes: [
      { unit: 'roti', grams: 40, label: '1 roti (40g)' },
      { unit: 'rotis', grams: 80, label: '2 rotis (80g)' },
    ],
    source: 'indian_db',
  },

  {
    name: 'Paratha',
    brand: 'Generic',
    calories_per_100g: 330,
    protein_per_100g: 7,
    carbs_per_100g: 45,
    fat_per_100g: 14,
    serving_sizes: [{ unit: 'paratha', grams: 80, label: '1 paratha (80g)' }],
    source: 'indian_db',
  },

  {
    name: 'Idli',
    brand: 'Generic',
    calories_per_100g: 146,
    protein_per_100g: 4.4,
    carbs_per_100g: 31,
    fat_per_100g: 0.4,
    serving_sizes: [
      { unit: 'idli', grams: 50, label: '1 idli (50g)' },
      { unit: 'idlis', grams: 100, label: '2 idli (100g)' },
    ],
    source: 'indian_db',
  },

  {
    name: 'Dosa',
    brand: 'Generic',
    calories_per_100g: 168,
    protein_per_100g: 4.5,
    carbs_per_100g: 28,
    fat_per_100g: 3.7,
    serving_sizes: [{ unit: 'dosa', grams: 120, label: '1 dosa (120g)' }],
    source: 'indian_db',
  },

  {
    name: 'Samosa',
    brand: 'Generic',
    calories_per_100g: 262,
    protein_per_100g: 5,
    carbs_per_100g: 31,
    fat_per_100g: 14,
    serving_sizes: [{ unit: 'samosa', grams: 100, label: '1 samosa (100g)' }],
    source: 'indian_db',
  },

  {
    name: 'Pani Puri',
    brand: 'Generic',
    calories_per_100g: 180,
    protein_per_100g: 4,
    carbs_per_100g: 32,
    fat_per_100g: 4,
    serving_sizes: [
      { unit: 'puri', grams: 20, label: '1 pani puri' },
      { unit: 'plate', grams: 120, label: '1 plate (6 puri)' },
    ],
    source: 'indian_db',
  },

  {
    name: 'Vada Pav',
    brand: 'Generic',
    calories_per_100g: 280,
    protein_per_100g: 7,
    carbs_per_100g: 36,
    fat_per_100g: 13,
    serving_sizes: [{ unit: 'vada pav', grams: 150, label: '1 vada pav' }],
    source: 'indian_db',
  },

  {
    name: 'Burger',
    brand: 'Generic',
    calories_per_100g: 295,
    protein_per_100g: 17,
    carbs_per_100g: 30,
    fat_per_100g: 12,
    serving_sizes: [{ unit: 'burger', grams: 200, label: '1 burger' }],
    source: 'restaurant',
  },

  {
    name: 'Chicken Momos',
    brand: 'Generic',
    calories_per_100g: 200,
    protein_per_100g: 12,
    carbs_per_100g: 24,
    fat_per_100g: 6,
    serving_sizes: [
      { unit: 'momo', grams: 35, label: '1 momo' },
      { unit: 'plate', grams: 210, label: '1 plate (6 momos)' },
    ],
    source: 'restaurant',
  },

  {
    name: 'Rasgulla',
    brand: 'Generic',
    calories_per_100g: 186,
    protein_per_100g: 3.6,
    carbs_per_100g: 45,
    fat_per_100g: 0.2,
    serving_sizes: [{ unit: 'rasgulla', grams: 50, label: '1 rasgulla' }],
    source: 'bengali_db',
  },

  {
    name: 'Sandesh',
    brand: 'Generic',
    calories_per_100g: 250,
    protein_per_100g: 6,
    carbs_per_100g: 30,
    fat_per_100g: 12,
    serving_sizes: [{ unit: 'sandesh', grams: 40, label: '1 sandesh' }],
    source: 'bengali_db',
  },

  {
    name: 'Protein Bar',
    brand: 'Generic',
    calories_per_100g: 380,
    protein_per_100g: 32,
    carbs_per_100g: 35,
    fat_per_100g: 12,
    serving_sizes: [{ unit: 'bar', grams: 60, label: '1 protein bar (60g)' }],
    source: 'supplement',
  },

  {
    name: 'Protein Cookie',
    brand: 'Generic',
    calories_per_100g: 420,
    protein_per_100g: 25,
    carbs_per_100g: 45,
    fat_per_100g: 18,
    serving_sizes: [{ unit: 'cookie', grams: 75, label: '1 protein cookie' }],
    source: 'supplement',
  },

  {
    name: 'Whey Protein',
    brand: 'Generic',
    calories_per_100g: 375,
    protein_per_100g: 80,
    carbs_per_100g: 8,
    fat_per_100g: 5,
    serving_sizes: [
      { unit: 'scoop', grams: 30, label: '1 scoop (30g)' },
      { unit: 'scoops', grams: 60, label: '2 scoops (60g)' },
    ],
    source: 'supplement',
  },
  {
    name: 'Egg Roll',
    brand: 'Generic',
    calories_per_100g: 260,
    protein_per_100g: 11,
    carbs_per_100g: 28,
    fat_per_100g: 13,
    serving_sizes: [
      { unit: 'roll', grams: 180, label: '1 egg roll (180g)' },
      { unit: 'rolls', grams: 360, label: '2 egg rolls (360g)' },
    ],
    source: 'street_food',
  },

  {
    name: 'Chicken Roll',
    brand: 'Generic',
    calories_per_100g: 270,
    protein_per_100g: 14,
    carbs_per_100g: 30,
    fat_per_100g: 12,
    serving_sizes: [
      { unit: 'roll', grams: 200, label: '1 chicken roll (200g)' },
      { unit: 'rolls', grams: 400, label: '2 chicken rolls (400g)' },
    ],
    source: 'street_food',
  },

  {
    name: 'Paneer Roll',
    brand: 'Generic',
    calories_per_100g: 280,
    protein_per_100g: 12,
    carbs_per_100g: 28,
    fat_per_100g: 15,
    serving_sizes: [
      { unit: 'roll', grams: 190, label: '1 paneer roll (190g)' },
      { unit: 'rolls', grams: 380, label: '2 paneer rolls (380g)' },
    ],
    source: 'street_food',
  },

  {
    name: 'Veg Roll',
    brand: 'Generic',
    calories_per_100g: 240,
    protein_per_100g: 7,
    carbs_per_100g: 32,
    fat_per_100g: 9,
    serving_sizes: [
      { unit: 'roll', grams: 170, label: '1 veg roll (170g)' },
      { unit: 'rolls', grams: 340, label: '2 veg rolls (340g)' },
    ],
    source: 'street_food',
  },

  {
    name: 'Kathi Roll',
    brand: 'Generic',
    calories_per_100g: 260,
    protein_per_100g: 12,
    carbs_per_100g: 30,
    fat_per_100g: 12,
    serving_sizes: [
      { unit: 'roll', grams: 190, label: '1 kathi roll (190g)' },
      { unit: 'rolls', grams: 380, label: '2 kathi rolls (380g)' },
    ],
    source: 'street_food',
  },
  {
    name: 'Dal Tadka',
    brand: 'Generic',
    calories_per_100g: 135,
    protein_per_100g: 8,
    carbs_per_100g: 18,
    fat_per_100g: 4,
    source: 'indian_db',
  },
  {
    name: 'Dal Makhani',
    brand: 'Generic',
    calories_per_100g: 200,
    protein_per_100g: 9,
    carbs_per_100g: 20,
    fat_per_100g: 10,
    source: 'indian_db',
  },
  {
    name: 'Rajma Curry',
    brand: 'Generic',
    calories_per_100g: 140,
    protein_per_100g: 8.7,
    carbs_per_100g: 20,
    fat_per_100g: 4,
    source: 'indian_db',
  },
  {
    name: 'Chole Curry',
    brand: 'Generic',
    calories_per_100g: 164,
    protein_per_100g: 9,
    carbs_per_100g: 27,
    fat_per_100g: 3,
    source: 'indian_db',
  },
  {
    name: 'Vegetable Pulao',
    brand: 'Generic',
    calories_per_100g: 160,
    protein_per_100g: 4,
    carbs_per_100g: 26,
    fat_per_100g: 4,
    source: 'indian_db',
  },
  {
    name: 'Jeera Rice',
    brand: 'Generic',
    calories_per_100g: 160,
    protein_per_100g: 3.5,
    carbs_per_100g: 30,
    fat_per_100g: 3,
    source: 'indian_db',
  },
  {
    name: 'Curd Rice',
    brand: 'Generic',
    calories_per_100g: 140,
    protein_per_100g: 4,
    carbs_per_100g: 22,
    fat_per_100g: 4,
    source: 'indian_db',
  },
  {
    name: 'Paneer Butter Masala',
    brand: 'Generic',
    calories_per_100g: 300,
    protein_per_100g: 10,
    carbs_per_100g: 10,
    fat_per_100g: 25,
    source: 'indian_db',
  },
  {
    name: 'Palak Paneer',
    brand: 'Generic',
    calories_per_100g: 180,
    protein_per_100g: 9,
    carbs_per_100g: 8,
    fat_per_100g: 12,
    source: 'indian_db',
  },
  {
    name: 'Paneer Bhurji',
    brand: 'Generic',
    calories_per_100g: 210,
    protein_per_100g: 12,
    carbs_per_100g: 6,
    fat_per_100g: 15,
    source: 'indian_db',
  },
  {
    name: 'Chicken Curry',
    brand: 'Generic',
    calories_per_100g: 220,
    protein_per_100g: 20,
    carbs_per_100g: 5,
    fat_per_100g: 14,
    source: 'indian_db',
  },
  {
    name: 'Butter Chicken',
    brand: 'Generic',
    calories_per_100g: 250,
    protein_per_100g: 18,
    carbs_per_100g: 6,
    fat_per_100g: 18,
    source: 'indian_db',
  },
  {
    name: 'Tandoori Chicken',
    brand: 'Generic',
    calories_per_100g: 195,
    protein_per_100g: 28,
    carbs_per_100g: 2,
    fat_per_100g: 8,
    source: 'indian_db',
  },
  {
    name: 'Chicken Tikka',
    brand: 'Generic',
    calories_per_100g: 180,
    protein_per_100g: 27,
    carbs_per_100g: 2,
    fat_per_100g: 7,
    source: 'indian_db',
  },
  {
    name: 'Mutton Curry',
    brand: 'Generic',
    calories_per_100g: 260,
    protein_per_100g: 18,
    carbs_per_100g: 5,
    fat_per_100g: 20,
    source: 'indian_db',
  },

  /* ---------------- BENGALI DISHES ---------------- */

  {
    name: 'Macher Jhol',
    brand: 'Generic',
    calories_per_100g: 110,
    protein_per_100g: 15,
    carbs_per_100g: 4,
    fat_per_100g: 4,
    source: 'bengali_db',
  },
  {
    name: 'Shorshe Ilish',
    brand: 'Generic',
    calories_per_100g: 320,
    protein_per_100g: 22,
    carbs_per_100g: 3,
    fat_per_100g: 25,
    source: 'bengali_db',
  },
  {
    name: 'Chingri Malai Curry',
    brand: 'Generic',
    calories_per_100g: 210,
    protein_per_100g: 18,
    carbs_per_100g: 6,
    fat_per_100g: 12,
    source: 'bengali_db',
  },
  {
    name: 'Kosho Mangsho',
    brand: 'Generic',
    calories_per_100g: 290,
    protein_per_100g: 20,
    carbs_per_100g: 6,
    fat_per_100g: 20,
    source: 'bengali_db',
  },
  {
    name: 'Chicken Kosha',
    brand: 'Generic',
    calories_per_100g: 250,
    protein_per_100g: 22,
    carbs_per_100g: 5,
    fat_per_100g: 16,
    source: 'bengali_db',
  },
  {
    name: 'Alur Dom',
    brand: 'Generic',
    calories_per_100g: 180,
    protein_per_100g: 3,
    carbs_per_100g: 24,
    fat_per_100g: 8,
    source: 'bengali_db',
  },
  {
    name: 'Begun Bhaja',
    brand: 'Generic',
    calories_per_100g: 240,
    protein_per_100g: 3,
    carbs_per_100g: 18,
    fat_per_100g: 16,
    source: 'bengali_db',
  },
  {
    name: 'Shukto',
    brand: 'Generic',
    calories_per_100g: 95,
    protein_per_100g: 3,
    carbs_per_100g: 12,
    fat_per_100g: 4,
    source: 'bengali_db',
  },
  {
    name: 'Mochar Ghonto',
    brand: 'Generic',
    calories_per_100g: 150,
    protein_per_100g: 4,
    carbs_per_100g: 18,
    fat_per_100g: 6,
    source: 'bengali_db',
  },
  {
    name: 'Mishti Doi',
    brand: 'Generic',
    calories_per_100g: 150,
    protein_per_100g: 4,
    carbs_per_100g: 22,
    fat_per_100g: 5,
    source: 'bengali_db',
  },

  /* ---------------- INDIAN STREET FOOD ---------------- */

  {
    name: 'Bhel Puri',
    brand: 'Generic',
    calories_per_100g: 150,
    protein_per_100g: 5,
    carbs_per_100g: 28,
    fat_per_100g: 2,
    source: 'street_food',
  },
  {
    name: 'Sev Puri',
    brand: 'Generic',
    calories_per_100g: 210,
    protein_per_100g: 6,
    carbs_per_100g: 32,
    fat_per_100g: 7,
    source: 'street_food',
  },
  {
    name: 'Dahi Puri',
    brand: 'Generic',
    calories_per_100g: 195,
    protein_per_100g: 6,
    carbs_per_100g: 28,
    fat_per_100g: 7,
    source: 'street_food',
  },
  {
    name: 'Aloo Tikki Chaat',
    brand: 'Generic',
    calories_per_100g: 210,
    protein_per_100g: 4,
    carbs_per_100g: 30,
    fat_per_100g: 8,
    source: 'street_food',
  },
  {
    name: 'Papdi Chaat',
    brand: 'Generic',
    calories_per_100g: 240,
    protein_per_100g: 6,
    carbs_per_100g: 35,
    fat_per_100g: 9,
    source: 'street_food',
  },
  {
    name: 'Momos Veg',
    brand: 'Generic',
    calories_per_100g: 170,
    protein_per_100g: 6,
    carbs_per_100g: 30,
    fat_per_100g: 2,
    source: 'street_food',
  },
  {
    name: 'Momos Chicken',
    brand: 'Generic',
    calories_per_100g: 200,
    protein_per_100g: 12,
    carbs_per_100g: 24,
    fat_per_100g: 6,
    source: 'street_food',
  },

  /* ---------------- RESTAURANT STYLE FOODS ---------------- */

  {
    name: 'Chicken Fried Rice',
    brand: 'Restaurant',
    calories_per_100g: 180,
    protein_per_100g: 8,
    carbs_per_100g: 28,
    fat_per_100g: 5,
    source: 'restaurant',
  },
  {
    name: 'Veg Fried Rice',
    brand: 'Restaurant',
    calories_per_100g: 165,
    protein_per_100g: 5,
    carbs_per_100g: 30,
    fat_per_100g: 4,
    source: 'restaurant',
  },
  {
    name: 'Chicken Noodles',
    brand: 'Restaurant',
    calories_per_100g: 190,
    protein_per_100g: 9,
    carbs_per_100g: 30,
    fat_per_100g: 5,
    source: 'restaurant',
  },
  {
    name: 'Veg Noodles',
    brand: 'Restaurant',
    calories_per_100g: 170,
    protein_per_100g: 5,
    carbs_per_100g: 32,
    fat_per_100g: 4,
    source: 'restaurant',
  },
  {
    name: 'Chilli Chicken',
    brand: 'Restaurant',
    calories_per_100g: 210,
    protein_per_100g: 18,
    carbs_per_100g: 10,
    fat_per_100g: 11,
    source: 'restaurant',
  },
  {
    name: 'Paneer Chilli',
    brand: 'Restaurant',
    calories_per_100g: 220,
    protein_per_100g: 11,
    carbs_per_100g: 12,
    fat_per_100g: 15,
    source: 'restaurant',
  },
  {
    name: 'Manchurian Veg',
    brand: 'Restaurant',
    calories_per_100g: 210,
    protein_per_100g: 6,
    carbs_per_100g: 30,
    fat_per_100g: 9,
    source: 'restaurant',
  },
  {
    name: 'Chicken Manchurian',
    brand: 'Restaurant',
    calories_per_100g: 230,
    protein_per_100g: 18,
    carbs_per_100g: 12,
    fat_per_100g: 14,
    source: 'restaurant',
  },

  /* ---------------- SUPPLEMENTS ---------------- */

  {
    name: 'Whey Protein Isolate',
    brand: 'Generic',
    calories_per_100g: 360,
    protein_per_100g: 90,
    carbs_per_100g: 3,
    fat_per_100g: 1,
    source: 'supplement',
  },
  {
    name: 'Mass Gainer',
    brand: 'Generic',
    calories_per_100g: 380,
    protein_per_100g: 20,
    carbs_per_100g: 65,
    fat_per_100g: 5,
    source: 'supplement',
  },
  {
    name: 'Creatine Monohydrate',
    brand: 'Generic',
    calories_per_100g: 0,
    protein_per_100g: 0,
    carbs_per_100g: 0,
    fat_per_100g: 0,
    source: 'supplement',
  },
  {
    name: 'BCAA Powder',
    brand: 'Generic',
    calories_per_100g: 400,
    protein_per_100g: 100,
    carbs_per_100g: 0,
    fat_per_100g: 0,
    source: 'supplement',
  },
  {
    name: 'EAA Powder',
    brand: 'Generic',
    calories_per_100g: 400,
    protein_per_100g: 100,
    carbs_per_100g: 0,
    fat_per_100g: 0,
    source: 'supplement',
  },
  {
    name: 'Pre Workout Powder',
    brand: 'Generic',
    calories_per_100g: 50,
    protein_per_100g: 0,
    carbs_per_100g: 12,
    fat_per_100g: 0,
    source: 'supplement',
  },

  /* ---------------- PACKAGED FOODS ---------------- */

  {
    name: 'Instant Noodles',
    brand: 'Generic',
    calories_per_100g: 470,
    protein_per_100g: 9,
    carbs_per_100g: 60,
    fat_per_100g: 20,
    source: 'packaged',
  },
  {
    name: 'Potato Chips',
    brand: 'Generic',
    calories_per_100g: 536,
    protein_per_100g: 7,
    carbs_per_100g: 53,
    fat_per_100g: 35,
    source: 'packaged',
  },
  {
    name: 'Chocolate Milk Drink',
    brand: 'Generic',
    calories_per_100g: 85,
    protein_per_100g: 3.2,
    carbs_per_100g: 12,
    fat_per_100g: 3,
    source: 'packaged',
  },
  {
    name: 'Chocolate Spread',
    brand: 'Generic',
    calories_per_100g: 540,
    protein_per_100g: 6,
    carbs_per_100g: 57,
    fat_per_100g: 31,
    source: 'packaged',
  },
  {
    name: 'Breakfast Cereal',
    brand: 'Generic',
    calories_per_100g: 380,
    protein_per_100g: 7,
    carbs_per_100g: 84,
    fat_per_100g: 2,
    source: 'packaged',
  },

  /* -------- FRUITS -------- */

  {
    name: 'Strawberries',
    brand: 'Generic',
    calories_per_100g: 32,
    protein_per_100g: 0.7,
    carbs_per_100g: 7.7,
    fat_per_100g: 0.3,
    source: 'usda',
  },
  {
    name: 'Blueberries',
    brand: 'Generic',
    calories_per_100g: 57,
    protein_per_100g: 0.7,
    carbs_per_100g: 14,
    fat_per_100g: 0.3,
    source: 'usda',
  },
  {
    name: 'Blackberries',
    brand: 'Generic',
    calories_per_100g: 43,
    protein_per_100g: 1.4,
    carbs_per_100g: 10,
    fat_per_100g: 0.5,
    source: 'usda',
  },
  {
    name: 'Raspberries',
    brand: 'Generic',
    calories_per_100g: 52,
    protein_per_100g: 1.2,
    carbs_per_100g: 12,
    fat_per_100g: 0.7,
    source: 'usda',
  },
  {
    name: 'Lychee',
    brand: 'Generic',
    calories_per_100g: 66,
    protein_per_100g: 0.8,
    carbs_per_100g: 17,
    fat_per_100g: 0.4,
    source: 'usda',
  },
  {
    name: 'Dragon Fruit',
    brand: 'Generic',
    calories_per_100g: 60,
    protein_per_100g: 1.2,
    carbs_per_100g: 13,
    fat_per_100g: 0.1,
    source: 'usda',
  },

  /* -------- GRAINS -------- */

  {
    name: 'White Rice Cooked',
    brand: 'Generic',
    calories_per_100g: 130,
    protein_per_100g: 2.7,
    carbs_per_100g: 28,
    fat_per_100g: 0.3,
    source: 'usda',
  },
  {
    name: 'Brown Rice Cooked',
    brand: 'Generic',
    calories_per_100g: 123,
    protein_per_100g: 2.7,
    carbs_per_100g: 26,
    fat_per_100g: 1,
    source: 'usda',
  },
  {
    name: 'Oats Raw',
    brand: 'Generic',
    calories_per_100g: 389,
    protein_per_100g: 16.9,
    carbs_per_100g: 66,
    fat_per_100g: 6.9,
    source: 'usda',
  },
  {
    name: 'Quinoa',
    brand: 'Generic',
    calories_per_100g: 368,
    protein_per_100g: 14,
    carbs_per_100g: 64,
    fat_per_100g: 6,
    source: 'usda',
  },
  {
    name: 'Barley',
    brand: 'Generic',
    calories_per_100g: 354,
    protein_per_100g: 12,
    carbs_per_100g: 73,
    fat_per_100g: 2.3,
    source: 'usda',
  },
  {
    name: 'Millet',
    brand: 'Generic',
    calories_per_100g: 378,
    protein_per_100g: 11,
    carbs_per_100g: 73,
    fat_per_100g: 4.2,
    source: 'usda',
  },

  /* -------- PROTEINS -------- */

  {
    name: 'Ground Beef',
    brand: 'Generic',
    calories_per_100g: 250,
    protein_per_100g: 26,
    carbs_per_100g: 0,
    fat_per_100g: 17,
    source: 'usda',
  },
  {
    name: 'Pork Chop',
    brand: 'Generic',
    calories_per_100g: 231,
    protein_per_100g: 25,
    carbs_per_100g: 0,
    fat_per_100g: 14,
    source: 'usda',
  },
  {
    name: 'Turkey',
    brand: 'Generic',
    calories_per_100g: 189,
    protein_per_100g: 29,
    carbs_per_100g: 0,
    fat_per_100g: 7,
    source: 'usda',
  },
  {
    name: 'Sardines',
    brand: 'Generic',
    calories_per_100g: 208,
    protein_per_100g: 25,
    carbs_per_100g: 0,
    fat_per_100g: 11,
    source: 'usda',
  },
  {
    name: 'Anchovies',
    brand: 'Generic',
    calories_per_100g: 210,
    protein_per_100g: 29,
    carbs_per_100g: 0,
    fat_per_100g: 10,
    source: 'usda',
  },
  {
    name: 'Tofu',
    brand: 'Generic',
    calories_per_100g: 76,
    protein_per_100g: 8,
    carbs_per_100g: 1.9,
    fat_per_100g: 4.8,
    source: 'usda',
  },
  {
    name: 'Tempeh',
    brand: 'Generic',
    calories_per_100g: 193,
    protein_per_100g: 20,
    carbs_per_100g: 9,
    fat_per_100g: 11,
    source: 'usda',
  },

  /* -------- LEGUMES -------- */

  {
    name: 'Black Beans',
    brand: 'Generic',
    calories_per_100g: 132,
    protein_per_100g: 8.9,
    carbs_per_100g: 24,
    fat_per_100g: 0.5,
    source: 'usda',
  },
  {
    name: 'Kidney Beans',
    brand: 'Generic',
    calories_per_100g: 127,
    protein_per_100g: 8.7,
    carbs_per_100g: 23,
    fat_per_100g: 0.5,
    source: 'usda',
  },
  {
    name: 'Lentils',
    brand: 'Generic',
    calories_per_100g: 116,
    protein_per_100g: 9,
    carbs_per_100g: 20,
    fat_per_100g: 0.4,
    source: 'usda',
  },
  {
    name: 'Chickpeas',
    brand: 'Generic',
    calories_per_100g: 164,
    protein_per_100g: 9,
    carbs_per_100g: 27,
    fat_per_100g: 2.6,
    source: 'usda',
  },

  /* -------- INDIAN DISHES -------- */

  {
    name: 'Khichdi',
    brand: 'Generic',
    calories_per_100g: 120,
    protein_per_100g: 4,
    carbs_per_100g: 22,
    fat_per_100g: 2,
    source: 'indian_db',
  },
  {
    name: 'Poha',
    brand: 'Generic',
    calories_per_100g: 130,
    protein_per_100g: 2.6,
    carbs_per_100g: 28,
    fat_per_100g: 1,
    source: 'indian_db',
  },
  {
    name: 'Upma',
    brand: 'Generic',
    calories_per_100g: 124,
    protein_per_100g: 3.5,
    carbs_per_100g: 21,
    fat_per_100g: 2.7,
    source: 'indian_db',
  },
  {
    name: 'Masala Dosa',
    brand: 'Generic',
    calories_per_100g: 180,
    protein_per_100g: 4.8,
    carbs_per_100g: 29,
    fat_per_100g: 4,
    source: 'indian_db',
  },
  {
    name: 'Sambar',
    brand: 'Generic',
    calories_per_100g: 75,
    protein_per_100g: 3,
    carbs_per_100g: 12,
    fat_per_100g: 2,
    source: 'indian_db',
  },
  {
    name: 'Chicken Biryani',
    brand: 'Generic',
    calories_per_100g: 222,
    protein_per_100g: 11,
    carbs_per_100g: 28,
    fat_per_100g: 8,
    source: 'indian_db',
  },
  {
    name: 'Mutton Biryani',
    brand: 'Generic',
    calories_per_100g: 250,
    protein_per_100g: 12,
    carbs_per_100g: 26,
    fat_per_100g: 12,
    source: 'indian_db',
  },
  {
    name: 'Veg Biryani',
    brand: 'Generic',
    calories_per_100g: 180,
    protein_per_100g: 4,
    carbs_per_100g: 30,
    fat_per_100g: 5,
    source: 'indian_db',
  },

  /* -------- BENGALI SWEETS -------- */

  {
    name: 'Rasmalai',
    brand: 'Generic',
    calories_per_100g: 250,
    protein_per_100g: 6,
    fat_per_100g: 15,
    carbs_per_100g: 24,
    source: 'bengali_db',
  },
  {
    name: 'Cham Cham',
    brand: 'Generic',
    calories_per_100g: 290,
    protein_per_100g: 6,
    fat_per_100g: 12,
    carbs_per_100g: 40,
    source: 'bengali_db',
  },
  {
    name: 'Pantua',
    brand: 'Generic',
    calories_per_100g: 300,
    protein_per_100g: 4,
    fat_per_100g: 15,
    carbs_per_100g: 38,
    source: 'bengali_db',
  },
  {
    name: 'Kalakand',
    brand: 'Generic',
    calories_per_100g: 280,
    protein_per_100g: 8,
    fat_per_100g: 15,
    carbs_per_100g: 28,
    source: 'bengali_db',
  },

  /* -------- COOKING FATS -------- */

  {
    name: 'Olive Oil',
    brand: 'Generic',
    calories_per_100g: 884,
    protein_per_100g: 0,
    carbs_per_100g: 0,
    fat_per_100g: 100,
    source: 'usda',
  },
  {
    name: 'Butter',
    brand: 'Generic',
    calories_per_100g: 717,
    protein_per_100g: 0.9,
    carbs_per_100g: 0.1,
    fat_per_100g: 81,
    source: 'usda',
  },
  {
    name: 'Ghee',
    brand: 'Generic',
    calories_per_100g: 900,
    protein_per_100g: 0,
    carbs_per_100g: 0,
    fat_per_100g: 100,
    source: 'usda',
  },
  {
    name: 'Sunflower Oil',
    brand: 'Generic',
    calories_per_100g: 884,
    protein_per_100g: 0,
    carbs_per_100g: 0,
    fat_per_100g: 100,
    source: 'usda',
  },
  {
    name: 'Coconut Oil',
    brand: 'Generic',
    calories_per_100g: 892,
    protein_per_100g: 0,
    carbs_per_100g: 0,
    fat_per_100g: 100,
    source: 'usda',
  },

  {
    name: 'Avocado',
    brand: 'Generic',
    calories_per_100g: 160,
    protein_per_100g: 2,
    carbs_per_100g: 9,
    fat_per_100g: 15,
    source: 'usda',
  },
  {
    name: 'Cabbage',
    brand: 'Generic',
    calories_per_100g: 25,
    protein_per_100g: 1.3,
    carbs_per_100g: 6,
    fat_per_100g: 0.1,
    source: 'usda',
  },
  {
    name: 'Beetroot',
    brand: 'Generic',
    calories_per_100g: 43,
    protein_per_100g: 1.6,
    carbs_per_100g: 10,
    fat_per_100g: 0.2,
    source: 'usda',
  },
  {
    name: 'Zucchini',
    brand: 'Generic',
    calories_per_100g: 17,
    protein_per_100g: 1.2,
    carbs_per_100g: 3.1,
    fat_per_100g: 0.3,
    source: 'usda',
  },
  {
    name: 'Eggplant',
    brand: 'Generic',
    calories_per_100g: 25,
    protein_per_100g: 1,
    carbs_per_100g: 6,
    fat_per_100g: 0.2,
    source: 'usda',
  },
  {
    name: 'Radish',
    brand: 'Generic',
    calories_per_100g: 16,
    protein_per_100g: 0.7,
    carbs_per_100g: 3.4,
    fat_per_100g: 0.1,
    source: 'usda',
  },
  {
    name: 'Turnip',
    brand: 'Generic',
    calories_per_100g: 28,
    protein_per_100g: 0.9,
    carbs_per_100g: 6.4,
    fat_per_100g: 0.1,
    source: 'usda',
  },
  {
    name: 'Green Peas',
    brand: 'Generic',
    calories_per_100g: 81,
    protein_per_100g: 5.4,
    carbs_per_100g: 14,
    fat_per_100g: 0.4,
    source: 'usda',
  },
  {
    name: 'Corn',
    brand: 'Generic',
    calories_per_100g: 96,
    protein_per_100g: 3.4,
    carbs_per_100g: 21,
    fat_per_100g: 1.5,
    source: 'usda',
  },
  {
    name: 'Mushroom',
    brand: 'Generic',
    calories_per_100g: 22,
    protein_per_100g: 3.1,
    carbs_per_100g: 3.3,
    fat_per_100g: 0.3,
    source: 'usda',
  },
  {
    name: 'Pumpkin',
    brand: 'Generic',
    calories_per_100g: 26,
    protein_per_100g: 1,
    carbs_per_100g: 7,
    fat_per_100g: 0.1,
    source: 'usda',
  },
  {
    name: 'Bottle Gourd',
    brand: 'Generic',
    calories_per_100g: 14,
    protein_per_100g: 0.6,
    carbs_per_100g: 3.4,
    fat_per_100g: 0.1,
    source: 'indian_db',
  },
  {
    name: 'Bitter Gourd',
    brand: 'Generic',
    calories_per_100g: 17,
    protein_per_100g: 1,
    carbs_per_100g: 3.7,
    fat_per_100g: 0.2,
    source: 'indian_db',
  },
  {
    name: 'Drumstick',
    brand: 'Generic',
    calories_per_100g: 37,
    protein_per_100g: 2.1,
    carbs_per_100g: 8,
    fat_per_100g: 0.2,
    source: 'indian_db',
  },
  {
    name: 'Lady Finger',
    brand: 'Generic',
    calories_per_100g: 33,
    protein_per_100g: 1.9,
    carbs_per_100g: 7.5,
    fat_per_100g: 0.2,
    source: 'indian_db',
  },
  {
    name: 'Cluster Beans',
    brand: 'Generic',
    calories_per_100g: 16,
    protein_per_100g: 3,
    carbs_per_100g: 10,
    fat_per_100g: 0.4,
    source: 'indian_db',
  },
  {
    name: 'Snake Gourd',
    brand: 'Generic',
    calories_per_100g: 18,
    protein_per_100g: 0.5,
    carbs_per_100g: 4,
    fat_per_100g: 0.1,
    source: 'indian_db',
  },
  {
    name: 'Ridge Gourd',
    brand: 'Generic',
    calories_per_100g: 20,
    protein_per_100g: 0.6,
    carbs_per_100g: 4.4,
    fat_per_100g: 0.1,
    source: 'indian_db',
  },
  {
    name: 'Ash Gourd',
    brand: 'Generic',
    calories_per_100g: 13,
    protein_per_100g: 0.4,
    carbs_per_100g: 3,
    fat_per_100g: 0.1,
    source: 'indian_db',
  },
  {
    name: 'Spring Onion',
    brand: 'Generic',
    calories_per_100g: 32,
    protein_per_100g: 1.8,
    carbs_per_100g: 7.3,
    fat_per_100g: 0.2,
    source: 'usda',
  },
]

async function seedFoods() {
  try {
    console.log('🔌 Connecting to database...')
    await connectDB()

    console.log('🔍 Checking existing foods...')

    const existingFoods = await Food.find({}, { name: 1 })
    const existingNames = new Set(
      existingFoods.map((f) => f.name.toLowerCase()),
    )

    const categoryMap: Record<string, string> = {
      usda: 'ingredient',
      open_food_facts: 'packaged',
      custom: 'ingredient',
      indian_db: 'meal',
      bengali_db: 'meal',
      street_food: 'street_food',
      restaurant: 'restaurant',
      supplement: 'supplement',
      packaged: 'packaged',
    }

    const regionMap: Record<string, string> = {
      usda: 'global',
      open_food_facts: 'global',
      custom: 'global',
      indian_db: 'indian',
      bengali_db: 'bengali',
      street_food: 'indian',
      restaurant: 'global',
      supplement: 'global',
      packaged: 'global',
    }

    // Remove duplicates + enrich data
    const foodsToInsert = commonFoods
      .filter((food) => !existingNames.has(food.name.toLowerCase()))
      .map((food) => ({
        ...food,
        category: categoryMap[food.source] || 'ingredient',
        region: regionMap[food.source] || 'global',
      }))

    if (foodsToInsert.length === 0) {
      console.log('⚠️ All foods already exist. Nothing to seed.')
      process.exit(0)
    }

    console.log(`🌱 Seeding ${foodsToInsert.length} foods...`)

    const result = await Food.insertMany(foodsToInsert)

    console.log(`✅ Successfully seeded ${result.length} foods!`)

    console.log('📦 Sample foods:')
    result.slice(0, 10).forEach((food) => {
      console.log(
        `  - ${food.name}: ${food.calories_per_100g} kcal | P:${food.protein_per_100g}g C:${food.carbs_per_100g}g F:${food.fat_per_100g}g`,
      )
    })

    console.log('🎉 Food seed complete.')

    process.exit(0)
  } catch (error) {
    console.error('❌ Error seeding foods:', error)
    process.exit(1)
  }
}

seedFoods()
